spring.application.name=PCBuilde
spring.datasource.url=jdbc:postgresql://localhost:5432/stockmanagementdatabase
spring.datasource.username=postgres
spring.datasource.password=papa19011981
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ????? ?????????
logging.level.root=INFO
logging.level.com.example.stockmanagementbackend=DEBUG

# ?????? ?????: ???? | ?????? | ????? | ???? : ????????????
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [%X{traceId}] - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [%X{traceId}] - %msg%n

# ???? ????? ?? ??????? (85%)
logging.file.name=logs/stock-app.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7

# ???????? Hibernate ???????? ????????? ?? SQL
spring.jpa.properties.hibernate.use_sql_comments=true

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG